# 该文件中配置红包服务的测试环境配置数据
red:
  remark: '{cipher}AQCej/gDyMdvnN4E21IcqnggHrKO9zDXiOOLdL7shQ6Pjx1KWUXKM/DAgPcaaYGa2GmXgYjJ7k/ibbNiJRiTPVehCfKW8h4K/KsUyXLtJHkMrYgGPb2zqKzP9GOVILYGaiiLAtmjlNolOW+OLmCpXylHibmso3Gv9U0bzCFQqdtADczHgqlm/CbkFTJtOoR9EC2440XnNdKRujeHhJN0ODEWIOW+sfYYsg+capGWrrSN30GSX487jP7dX04x8F23idwUFE0p65UgNcc9F564d8jAop40XMKBwbpTjO7mTZNzIIsA5VOsFdJumrxM40J8ZzzWCryLTxy1ZOK7uf0qvGR+69Oq/fnKbD4wFdjCeAd3v3oPPrSPAxbO3Ihve8tU06k='
