# 该文件中配置红包服务的测试环境配置数据
red:
  remark: '{cipher}AQAyjaR6a70E6xnI81bkoDeX51XIEWId0vrComDdliwySaT7PJIjfm1FBI8WT77t8ALz0zbRMujN7FVpWvWWmQ1jk7H9dQnFaR3sbxqbDBqt8foAhBGh78kcf/7J69/Fq8LK+cifna9rJ23cOF3SeRgKKPmMO/iLtdnqWxNXMmiioZb+C4FKuujVuYsUMlCNFs1lZXThT5CKWGPUPHSpUSSIjjZFbz1SBcRT+9x6jnbC0efa2nHX9IsMIvTLl6jQ3AveDMSCFxR0Aj6k8g7GFrVu6BNwAvJkSJUp71E5VF5ueGVwQm60IZjnnsIZrhhAEEWOjiCzvjHIFiZejLgCaxqGnmwK2GFQjrwVMu8V9mg/RspcbH/xMkrUzekrvaWIA/w='
